# =============================================
# Configuraci�n de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=

# =============================================
# Configuracin SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=melany.olivera211@gmail.com
smtp.password=degs mzmq jegj qihx
smtp.from.address=melany.olivera211@gmail.com
smtp.from.name=Melany
